# Generated by Django 6.0.6 on 2026-07-05 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Davis Carpets', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(default='(336) 622-2222', max_length=20)),
                ('address', models.CharField(default='5639 NC Highway 49 N, Liberty, NC 27298', max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hours', models.CharField(default='Mon–Fri: 8AM – 5PM | Saturday: By Appointment', max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('years_in_business', models.IntegerField(default=78)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business Info',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('carpet', 'Carpet'), ('hardwood', 'Hardwood'), ('tile', 'Tile'), ('laminate', 'Laminate'), ('vinyl', 'Vinyl'), ('installation', 'Installation'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sort_order', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['sort_order', '-uploaded_at'],
            },
        ),
    ]
