# Generated by Django 6.0.6 on 2026-07-05 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openrouter_api_key', models.CharField(blank=True, default='', max_length=500)),
                ('openrouter_model', models.CharField(default='openai/gpt-4o-mini', help_text='Model from OpenRouter (e.g. openai/gpt-4o-mini, google/gemini-2.0-flash-free)', max_length=200)),
                ('system_prompt', models.TextField(default='You are a helpful assistant for Davis Carpets flooring company. Answer questions about flooring, carpet, tile, hardwood, laminate, and vinyl. Be friendly and professional.', help_text='System prompt for the AI chatbot')),
                ('site_title', models.CharField(default="Bryan's Dashboard", max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('session_id', models.CharField(default='default', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
