# Generated by Django 6.0.6 on 2026-07-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='alexander_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='alexander_promo_text',
            field=models.TextField(blank=True, default='', help_text='Promotional message shown when users give positive feedback'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='alexander_qr_code',
            field=models.URLField(blank=True, default='', help_text='URL to a QR code image that links to Alexander AI Solutions', max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='alexander_website',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='feedback_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='openrouter_model',
            field=models.CharField(default='openai/gpt-4o-mini', help_text='Model from OpenRouter', max_length=200),
        ),
    ]
